-- 코드를 입력하세요
SELECT A.APNT_NO, PN.PT_NAME, PN.PT_NO, A.MCDP_CD, DT.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT PN
ON A.PT_NO = PN.PT_NO
JOIN DOCTOR DT
ON A.MDDR_ID = DT.DR_ID
WHERE A.APNT_YMD LIKE "2022-04-13%" AND A.MCDP_CD = "CS" AND APNT_CNCL_YN = "N"
ORDER BY A.APNT_YMD